fun main() {
    /*Conditionals.ifCondition()
    Conditionals.whenCondition()
    println()
    Loops.whileLoop()
    println()
    Loops.doWhileLoop()
    println()
    Loops.forLoopFizzBuzz()*/
    println()
    Loops.findLetterL()
    println()
    println(Functions.circleArea(2))
    println()
    println(Functions.circleAreaSingleExpression(5))
    println()
    Functions.main()
    println()
    println(Lambdas.urls)
    println()
    Lambdas.invokeCustomRepeat()
    println()
    println()
    val employee = Classes.Employee("Osei",35)
    employee.salary+=10
    println(employee.name +" "+employee.salary )
}